var mongoose = require('mongoose');

module.exports = mongoose.model('Items', {
	id: {type: Number, required: true, unique: true},
	name: {type: String, required: true},
	plaintext: {type: String},
	sanitizedDescription: {type: String},
	depth: {type: Number},
	description: {type: String},
	from: [
		String
	],
	gold: {
		total: {type: Number},
		purchasable: {type: Boolean},
		sell: {type: Number},
		base: {type: Number}
	},
	group: {type: String},
	stats: {
		FlatSpellBlockMod: {type: Number},
		PercentMPRegenMod: {type: Number},
		rFlatSpellBlockModPerLevel: {type: Number},
		rFlatArmorModPerLevel: {type: Number},
		PercentPhysicalDamageMod: {type: Number},
		FlatCritChanceMod: {type: Number},
		PercentSpellBlockMod: {type: Number},
		rFlatTimeDeadModPerLevel: {type: Number},
		rFlatMagicDamageModPerLevel: {type: Number},
		rFlatHPModPerLevel: {type: Number},
		rPercentMovementSpeedModPerLevel: {type: Number},
		FlatEXPBonus: {type: Number},
		FlatMPRegenMod: {type: Number},
		rFlatHPRegenModPerLevel: {type: Number},
		FlatBlockMod: {type: Number},
		PercentEXPBonus: {type: Number},
		FlatEnergyPoolMod: {type: Number},
		rFlatEnergyRegenModPerLevel: {type: Number},
		rFlatGoldPer10Mod: {type: Number},
		FlatAttackSpeedMod: {type: Number},
		FlatHPPoolMod: {type: Number},
		PercentAttackSpeedMod: {type: Number},
		rFlatDodgeMod: {type: Number},
		rFlatMPRegenModPerLevel: {type: Number},
		rPercentTimeDeadMod: {type: Number},
		FlatEnergyRegenMod: {type: Number},
		PercentSpellVampMod: {type: Number},
		FlatCritDamageMod: {type: Number},
		rFlatMovementSpeedModPerLevel: {type: Number},
		PercentHPRegenMod: {type: Number},
		rPercentArmorPenetrationModPerLevel: {type: Number},
		PercentArmorMod: {type: Number},
		rFlatMPModPerLevel: {type: Number},
		rFlatArmorPenetrationMod: {type: Number},
		PercentBlockMod: {type: Number},
		PercentMagicDamageMod: {type: Number},
		FlatMPPoolMod: {type: Number},
		FlatPhysicalDamageMod: {type: Number},
		rFlatPhysicalDamageModPerLevel: {type: Number},
		rFlatTimeDeadMod: {type: Number},
		FlatHPRegenMod: {type: Number},
		rFlatCritDamageModPerLevel: {type: Number},
		rFlatCritChanceModPerLevel: {type: Number},
		rFlatDodgeModPerLevel: {type: Number},
		rPercentMagicPenetrationModPerLevel: {type: Number},
		PercentLifeStealMod: {type: Number},
		PercentMovementSpeedMod: {type: Number},
		FlatArmorMod: {type: Number},
		rFlatEnergyModPerLevel: {type: Number},
		rPercentMagicPenetrationMod: {type: Number},
		rPercentTimeDeadModPerLevel: {type: Number},
		PercentMPPoolMod: {type: Number},
		PercentDodgeMod: {type: Number},
		PercentCritChanceMod: {type: Number},
		PercentCritDamageMod: {type: Number},
		rPercentAttackSpeedModPerLevel: {type: Number},
		rFlatMagicPenetrationMod: {type: Number},
		PercentHPPoolMod: {type: Number},
		rPercentArmorPenetrationMod: {type: Number},
		rFlatMagicPenetrationModPerLevel: {type: Number},
		rFlatArmorPenetrationModPerLevel: {type: Number},
		rPercentCooldownModPerLevel: {type: Number},
		FlatMagicDamageMod: {type: Number},
		FlatMovementSpeedMod: {type: Number},
		rPercentCooldownMod: {type: Number}
	},
	image: {
		w: {type: Number},
		full: {type: String},
		sprite: {type: String},
		group: {type: String},
		h: {type: Number},
		y: {type: Number},
		x: {type: Number}
	}
});